version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "YourStrong!Passw0rd"
      MYSQL_DATABASE: "MyDatabase"

    ports:
      - "3306:3306"

  app:
    build: .
    volumes:
      - ./:/app
    container_name: myaspnetapp
    depends_on:
      - mysql
    ports:
      - "5000:5000"
    environment:
      PAGES_APP_ID: ${PAGES_APP_ID}
      PAGES_APP_SECRET: ${PAGES_APP_SECRET}
